@startuml
title Монолитное приложение Тёплый дом

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

' Название системы
System_Boundary(c1, "Монолитное приложение Тёплый дом") {
    Container(app, "Монолит на Go", "Web-приложение", "Управление отоплением и получение температуры. Подключение новых домов вручную")
    ContainerDb(db, "PostgreSQL", "Реляционная БД", "Хранит информацию о пользователях, домах, устройствах, температуре")
}

' Акторы
Person(user, "Пользователь", "Управляет отоплением через веб-интерфейс")
Person(technician, "Специалист", "Выезжает для подключения домов и настройки системы")
System_Ext(sensor, "Датчики отопления", "Передают температуру по запросу сервера")

' Связи
Rel(user, app, "Использует через веб-интерфейс")
Rel(technician, app, "Подключает вручную новые дома")
Rel(app, db, "Читает/пишет данные", "SQL")
Rel(app, sensor, "Запрашивает данные, управляет", "Синхронно (pull)")
@enduml
