@startuml
title "Тёплый дом" диаграмма контейнеров
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(user, "User", "A user of the system")

System(WarmHouseSystem, "Warm House System", "device management, device data collection, payment")
Container_Boundary(WarmHouseSystem, "Warm House System"){
    Container(WebApp, "Web Application", "Java, Spring", "Handles user interactions")
    Container(MobileApp, "Mobile Application", "Kotlin, Swift", "Allows users to control devices in their home. Receive data from devices")
    Container(PaymentService, "Payment Service", "Node.js", "Processes payments")
    Container(Database, "Database", "PostgreSQL", "Store user data, device data")
}

System_Ext(api, "External Devices")
System_Ext(bank, "Bank System", "External bank for processing payments")
System_Ext(notificationService, "Notification Service", "Provides users notificating")

Rel(user, WebApp, "Uses the system")
Rel(WebApp,PaymentService,"Processes payment requests")
Rel(PaymentService,bank,"Processes payments")
Rel(WebApp,Database,"Reads/Writes user data")
Rel(MobileApp,Database,"Reads/Writes user data")
Rel(WebApp,api,"Extracts device data")
Rel(WebApp,notificationService,"Send message")

@enduml
