@startuml
title SmartHome Microservices To-Be Container Diagram

top to bottom direction

!include https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Person(user, "User", "A user of the smart-home")

System_Boundary(SmartHomeSensors, "SmartHome sensors") {
    System_Ext(heating_sensors, "Heating sensors and controller", "")
    System_Ext(lighting_sensors, "Lighting sensors and controller", "")
    System_Ext(locking_sensors, "Locking sensors and controller", "")
    System_Ext(video_sensors, "Video sensors and controller", "")
}

System_Boundary(SmartHomeSystem, "SmartHome system") {
    Container(api_gateway, "API Gateway", "Routing queries.")

    Container(heating_system, "Heating system", "Configure, turn-on/off heating system, get/set temperature.")
    Container(lighting_system, "Lighting system", "Configure, turn-on/off lighting system.")
    Container(locking_system, "Locking system", "Configure, lock-in/out locking system.")
    Container(video_system, "Video system", "Configure, turn-on/off video system")

    ComponentDb(heating_db, "Heating system settings, sensor data", "PostgreSQL")
    ComponentDb(lighting_db, "Lighting system settings, sensor data", "PostgreSQL")
    ComponentDb(locking_db, "Locking system settings, sensor data", "PostgreSQL")
    ComponentDb(video_db, "Video system settings, sensor data", "PostgreSQL")
}

ComponentDb_Ext(cloud_storage, "Cloud storage", "AWS")

Rel(user, api_gateway, "Configure/Monitor SmartHome System")
Rel(api_gateway, heating_system, "")
Rel(api_gateway, lighting_system, "")
Rel(api_gateway, locking_system, "")
Rel(api_gateway, video_system, "")
Rel(heating_system, heating_db, "Add heating user config, telemetry data")
Rel(lighting_system, lighting_db, "Add lighting user config")
Rel(locking_system, locking_db, "Add locking user config")
Rel(video_system, video_db, "Add video user config")
Rel(heating_system, heating_sensors, "Get/Set temperature")
Rel(lighting_system, lighting_sensors, "Turn on/off")
Rel(locking_system, locking_sensors, "Lock-in/out")
Rel(video_system, video_sensors, "Turn on (get streaming data)/ turn-off, ")
Rel(video_system, cloud_storage, "Save video files")

@enduml