@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
title Диаграмма контекста для монолитного решения

Person(user, "User", "Пользователь системы отопления Теплый дом.")

Enterprise_Boundary(c0, "Управление устройствами") {
    System(system, "Сервис управления отоплением и проверки температуры", "Позволяет пользователям управлять отоплением и отслеживать температуру.")

    System_Ext(sensors, "Датчики", "Датчики различных систем отоплениия, позволяющие управлять отоплением и отслеживать температуру")

}

Rel_Neighbor(user, system, "Использует", API)
Rel_R(system, sensors, "Управляет", API)
Rel_Back(system, sensors, "Возвращает температуру", API)
@enduml