@startuml
title SmartHouse DeviceService Component Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Container_Boundary(SmartHouseSystem, "SmartHouse System") {
  Container(DeviceService, "Device Service", "Java, Spring", "Handles device interactions")
  Container(Database, "Database", "PostgreSQL", "Stores device data and telemetry")
}

Container(DeviceService, "Web Application", "Java, Spring") {
  Component(CommandController, "CommandController", "Handles commands for devices")
  Component(TelemetryController, "TelemetryController", "Handles requests to recieve device telemetry")
  Component(KafkaListener, "KafkaListener", "Listen for telemetry events from devices")
  Component(ServiceLayer, "Service Layer", "Business logic")
  Component(RepositoryLayer, "Repository Layer", "Data access logic")
}

Rel(CommandController,ServiceLayer,"Sends commands to specific user device")
Rel(TelemetryController,ServiceLayer,"Reads telemetry from specific device")
Rel(ServiceLayer,RepositoryLayer,"Reads/Writes data")
Rel(KafkaListener,RepositoryLayer,"Writes data")
Rel(RepositoryLayer,Database,"Reads/Writes user data")
@enduml