@startuml
title SmartHouse DeviceService Component Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Container_Boundary(SmartHouseSystem, "SmartHouse System") {
  Container(DeviceService, "Device Service", "Java, Spring", "Работа с устройствами и их модулями")
  Container(Database, "Database", "PostgreSQL", "Хранение данных устройств и телеметрии модулей")
}

Container(DeviceService, "Web Application", "Java, Spring") {
  Component(CommandController, "CommandController", "Обработка команд для модулей")
  Component(TelemetryController, "TelemetryController", "Получение телеметрии модулей")
  Component(KafkaListener, "KafkaListener", "Получение новых событий о телеметрии с устройств")
  Component(ServiceLayer, "Service Layer", "Слой бизнес логики")
  Component(RepositoryLayer, "Repository Layer", "Слой доступа к данным")
}

Rel(CommandController,ServiceLayer,"Изменение значения на определенном модуле устройства")
Rel(TelemetryController,ServiceLayer,"Получение телеметрии с модуля устройства")
Rel(ServiceLayer,RepositoryLayer,"Чтение/запись данных")
Rel(KafkaListener,RepositoryLayer,"Чтение/запись данных")
Rel(RepositoryLayer,Database,"Чтение/запись данных")
@enduml